CREATE TABLE SALESMAN 
(SALESMAN_ID INTEGER (4), 
NAME VARCHAR (20), 
CITY VARCHAR (20), 
COMMISSION VARCHAR (20), 
PRIMARY KEY (SALESMAN_ID));

CREATE TABLE CUSTOMER1 
(CUSTOMER_ID INTEGER (4), 
CUST_NAME VARCHAR (20), 
CITY VARCHAR (20), 
GRADE INTEGER (3), 
PRIMARY KEY (CUSTOMER_ID), 
SALESMAN_ID INTEGER REFERENCES SALESMAN (SALESMAN_ID) ON DELETE SET NULL);

CREATE TABLE ORDERS 
(ORD_NO INTEGER (5), 
PURCHASE_AMT INTEGER (10), 
ORD_DATE DATE, 
PRIMARY KEY (ORD_NO), 
CUSTOMER_ID INTEGER REFERENCES CUSTOMER1 (CUSTOMER_ID) ON DELETE CASCADE, 
SALESMAN_ID INTEGER REFERENCES SALESMAN (SALESMAN_ID) ON DELETE CASCADE);
