CREATE TABLE SALESMAN ( 
SALESMAN_ID INT (4) PRIMARY KEY, 
NAME VARCHAR (20), 
CITY VARCHAR (20), 
COMMISSION VARCHAR (20)); 

CREATE TABLE CUSTOMER ( 
CUSTOMER_ID INT (5) PRIMARY KEY, 
CUST_NAME VARCHAR (20), 
CITY VARCHAR (20), GRADE INT (4), 
SALESMAN_ID INT (6), 
FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN (SALESMAN_ID) ON DELETE 
SET NULL); 

CREATE TABLE ORDERS ( 
ORD_NO INT (5) PRIMARY KEY, 
PURCHASE_AMT DECIMAL (10, 2), 
ORD_DATE DATE, 
CUSTOMER_ID INT (4), 
SALESMAN_ID INT (4), 
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE 
CASCADE, 
FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN (SALESMAN_ID) ON DELETE 
CASCADE);
